export const JERSEYS = [
  "Ateneo Roca 1.png",
  "Ateneo Roca 2.png",
  "Ateneo Roca 3.png",
  "Ateneo Roca 4.png",
  "Bajo Belgrano 1.png",
  "Bajo Belgrano 2.png",
  "Belgrano 1(1).png",
  "Belgrano 1.png",
  "Belgrano 2.png",
  "Buen Ayre 1.png",
  "Buen Ayre 2.png",
  "Buen Camino 1.png",
  "Buen Camino 2.png",
  "CA San Damian 1.png",
  "CA San Damian 2.png",
  "CFI 2.png",
  "CFI 3.png",
  "Cartero 1.png",
  "Cartero 2.png",
  "Cb 12 de Octubre 1.png",
  "Cb 12 de Octubre 2.png",
  "Cb 12 de Octubre 3.png",
  "Cb 12 de Octubre 4.png",
  "Ciclon 1.png",
  "Ciclon 2.png",
  "Cristo Rey 1.png",
  "Cristo Rey 2.png",
  "Deportivo San Martin 1.png",
  "Deportivo San Martin 2.png",
  "Deportivo San Martin 3.png",
  "Deportivo San Martin 4.png",
  "EIDU 1.png",
  "EIDU 2.png",
  "EIDU 3.png",
  "EIDU 4.png",
  "El Destino 1.png",
  "El Destino 2.png",
  "Greppi 1.png",
  "Hurlingham FC 1.png",
  "Hurlingham FC 2.png",
  "Hurlingham Norte 1.png",
  "Hurlingham Norte 2.png",
  "Juventud Mitre 1.png",
  "Juventud Mitre 2.png",
  "La Juanita_Malvinas Fem. Inf. arquera.png",
  "La Juanita_Malvinas Fem. Inf. jugadora.png",
  "La Juanita_Malvinas Masc. Inf. arquero.png",
  "La Juanita_Malvinas Masc. Inf. jugador.png",
  "Libertador 1.png",
  "Libertador 2.png",
  "Libertador 3.png",
  "Libertador 4.png",
  "Los Patitos modelo.png",
  "Pampero 1.png",
  "Pampero 2.png",
  "Patitos 1.png",
  "Patitos 2.png",
  "Plaza Urquiza.png",
  "Quinta Los Pibes 1.png",
  "Quinta Los Pibes 2.png",
  "SF 18 de Julio 1.png",
  "SF 18 de Julio 2.png",
  "SF La Esperanza 1.png",
  "SF La Esperanza 2.png",
  "SF Primero de Mayo 1.png",
  "SF Primero de Mayo 2.png",
  "SF San Damian Fem. Inf. arquera.png",
  "SF San Damian Inf. Fem. jugadora.png",
  "Santa Leonor 1.png",
  "Santa Leonor 2.png",
  "Santa Leonor 3.png",
  "Santa Leonor 4.png",
  "Socie San Damian 3.png",
  "Socie San Damian 4.png",
  "Tinta 1.png",
  "Tinta 2.png",
  "Villa Club 1.png",
  "Villa Club 2.png",
] as const;

export type Jersey = (typeof JERSEYS)[number];

export function jerseyLabel(filename: Jersey | string): string {
  return filename.replace(/\.png$/i, "");
}

export function clubNameFromJersey(filename: Jersey | string): string {
  return filename.replace(/\.png$/i, "").replace(/\s+\d+(\(\d+\))?$/, "").trim();
}
